import './globals.scss'
import NavBar from "@/components/Navbar/Navbar";
import styles from './page.module.scss';
import { NextResponse } from 'next/server';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getData() {
  const res = await fetch('http://localhost:3000/api/boards');

  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  )
}
