import './globals.scss'
import NavBar from "@/components/Navbar/Navbar";
import styles from './page.module.scss';
import { cache } from 'react';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getData() {
  const res = await fetch('http://localhost:8008/home/boards', {cache: 'no-store'});

  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const data = await getData();
  console.log(data)

  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <NavBar data={data}/>
          {children}
        </div>
      </body>
    </html>
  )
}
