import './globals.scss'
import NavBar from "@/components/Navbar/Navbar";
import styles from './page.module.scss';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  )
}
